# -------------------
# TEMPLATE
# Copy this to ./config.toml and edit values as needed (see README for details)
# -------------------


[browser_setup]
captive_url = ""                              # (Optional) URL of the captive portal's login page
fallback_trigger_url = "http://neverssl.com"  # URL to trigger captive portal redirection if captive_url is not set or fails
headless = true                               # Whether to run the browser in headless mode (no GUI)
chrome_path = "/usr/bin/chrome"               # Use this for Chrome or Chromium
# firefox_path = "/Applications/Firefox.app/Contents/MacOS/firefox"  # Use this instead for Firefox
driver_path = "/usr/bin/chromedriver"         # (Optional) path to the corresponding WebDriver executable; omit it to let Selenium resolve/download the matching one at runtime

[retry]
attempts = 3
delay = 5     
timeout = 15                                  # Timeout for GET requests to check connection status (in seconds)

[login] 
credentials_file = "./credentials.txt"        # Path to the credentials file (see README for format)
sequence = [                                  # Sequence of actions to perform on the captive portal for login. (see README for format)
  { action = "click", selector = "a" },
  { action = "click", selector = "#cp-modal-button-member-simple" },
  { action = "fill-username", selector = "input:nth-of-type(1)" },
  { action = "fill-password", selector = "input:nth-of-type(2)" },
  { action = "click", selector = "button[type=\"submit\"]" },
]